backend:
  name: git-gateway
  branch: main

local_backend: false
publish_mode: editorial_workflow

media_folder: public/assets/images/blog
public_folder: /assets/images/blog

collections:
  - name: blog
    label: Blog
    folder: public/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: string }
      - { label: Body, name: body, widget: markdown }
